version: "3.7"

services:
  athena_mysql:
    image: mysql:8
    restart: always
    volumes:
      - ./_data/mysql:/var/lib/mysql
    env_file: ./.config/mysql.env
    ports:
      - "46120:3306"
    container_name: athena-mysql
  athena_redis:
    image: redis:6
    restart: always
    ports:
      - "46110:6379"
    volumes:
      - ./_data/redis:/data
    container_name: athena-redis
