version: "3.7"

services:
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - ./_data/mysql:/var/lib/mysql
      - ./.config/mysqlconf/athena.conf:/etc/mysql/athena.conf
    env_file: ./.config/mysql.env
    ports:
      - "46120:3306"
    container_name: athena-mysql
  redis:
    image: redis:6
    restart: always
    ports:
      - "46110:6379"
    volumes:
      - ./_data/redis:/data
    container_name: athena-redis
