CREATE TABLE `corporations` (
    `id` INT UNSIGNED NOT NULL,
    `name` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_unicode_ci',
    `ticker` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_unicode_ci',
    `ceo_id` INT UNSIGNED NOT NULL,
    `creator_id` INT UNSIGNED NOT NULL,
    `alliance_id` INT NULL DEFAULT NULL,
    `home_station_id` INT UNSIGNED NULL DEFAULT NULL,
    `faction_id` INT UNSIGNED NULL DEFAULT NULL,
    `member_count` INT UNSIGNED NOT NULL,
    `shares` BIGINT UNSIGNED NULL DEFAULT NULL,
    `tax_rate` FLOAT NOT NULL,
    `url` VARCHAR(255) NULL DEFAULT NULL,
    `war_eligible` TINYINT NOT NULL DEFAULT '0',
    `date_founded` TIMESTAMP NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL,
    PRIMARY KEY (`id`) USING BTREE,
    INDEX `corporation_ceo_id_idx` (`ceo_id`),
    INDEX `corporation_creator_id_idx` (`creator_id`),
    INDEX `corporations_alliance_id_idx` (`alliance_id`),
    INDEX `corporations_home_station_id_idx` (`home_station_id`),
    INDEX `corporations_faction_id_idx` (`faction_id`),
) COLLATE = 'utf8mb4_unicode_ci' ENGINE = InnoDB;