CREATE TABLE `characters` (
    `id` INT UNSIGNED NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `corporation_id` INT UNSIGNED NOT NULL,
    `alliance_id` INT UNSIGNED NULL DEFAULT NULL,
    `faction_id` INT UNSIGNED NULL DEFAULT NULL,
    `security_status` FLOAT NULL DEFAULT NULL,
    `gender` ENUM('male', 'female') NOT NULL,
    `birthday` TIMESTAMP NOT NULL,
    `title` VARCHAR(255) NULL DEFAULT NULL,
    `ancestry_id` INT UNSIGNED NOT NULL,
    `bloodline_id` INT UNSIGNED NOT NULL,
    `race_id` INT UNSIGNED NOT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `characters_corporation_id_idx` (`corporation_id`),
    INDEX `characters_alliance_id_idx` (`alliance_id`),
    INDEX `characters_faction_id_idx` (`faction_id`),
    INDEX `characters_ancestry_id_idx` (`ancestry_id`),
    INDEX `characters_bloodline_id_idx` (`bloodline_id`),
    INDEX `characters_race_id_idx` (`race_id`),
    CONSTRAINT `characters_corporation_id_corporations_id_foreign` FOREIGN KEY (`corporation_id`) REFERENCES `athena`.`corporations` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `characters_alliance_id_alliances_id_foreign` FOREIGN KEY (`alliance_id`) REFERENCES `athena`.`alliances`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `characters_faction_id_factions_id_foreign` FOREIGN KEY (`faction_id`) REFERENCES `athena`.`factions` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `characters_ancestry_id_ancestries_id_foreign` FOREIGN KEY (`ancestry_id`) REFERENCES `athena`.`ancestries` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `characters_bloodline_id_bloodlines_id_foreign` FOREIGN KEY (`bloodline_id`) REFERENCES `athena`.`bloodlines` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `characters_race_id_races_id_foreign` FOREIGN KEY (`race_id`) REFERENCES `athena`.`races` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
) COLLATE = 'utf8mb4_unicode_ci' ENGINE = InnoDB;