CREATE TABLE `member_contracts` (
    `member_id` INT UNSIGNED NOT NULL,
    `contract_id` INT UNSIGNED NOT NULL,
    `acceptor_id` INT UNSIGNED NULL DEFAULT NULL,
    `assignee_id` INT UNSIGNED NULL DEFAULT NULL,
    `availability` ENUM('public', 'personal', 'corporation', 'alliance') NOT NULL,
    `buyout` FLOAT NULL DEFAULT NULL,
    `collateral` FLOAT NULL DEFAULT NULL,
    `date_accepted` TIMESTAMP NULL DEFAULT NULL,
    `date_completed` TIMESTAMP NULL DEFAULT NULL,
    `date_expired` TIMESTAMP NOT NULL,
    `date_issued` TIMESTAMP NOT NULL,
    `days_to_complete` INT UNSIGNED NULL DEFAULT NULL,
    `end_location_id` BIGINT UNSIGNED NULL DEFAULT NULL,
    `for_corporation` TINYINT NOT NULL DEFAULT '0',
    `issuer_corporation_id` INT UNSIGNED NOT NULL,
    `issuer_id` INT UNSIGNED NOT NULL,
    `price` FLOAT NULL DEFAULT NULL,
    `reward` FLOAT NULL DEFAULT NULL,
    `start_location_id` BIGINT UNSIGNED NULL DEFAULT NULL,
    `status` ENUM(
        'outstanding',
        'in_progress',
        'finished_issuer',
        'finished_contractor',
        'finished',
        'cancelled',
        'rejected',
        'failed',
        'deleted',
        'reversed'
    ) NOT NULL,
    `title` VARCHAR(64) NULL DEFAULT NULL,
    `type` ENUM(
        'unknown',
        'item_exchange',
        'auction',
        'courier',
        'loan'
    ) NOT NULL,
    `volume` FLOAT NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL,
    PRIMARY KEY (`member_id`, `contract_id`) USING BTREE,
    INDEX `member_contracts_acceptor_id_idx` (`acceptor_id`) USING BTREE,
    INDEX `member_contracts_assignee_id_idx` (`assignee_id`) USING BTREE,
    INDEX `member_contracts_issuer_corporation_id_idx` (`issuer_corporation_id`) USING BTREE,
    INDEX `member_contracts_issuer_id_idx` (`issuer_id`) USING BTREE,
    INDEX `member_contracts_start_location_id_idx` (`start_location_id`) USING BTREE,
    INDEX `member_contracts_end_location_id_idx` (`end_location_id`) USING BTREE,
    CONSTRAINT `member_contracts_member_id_foreign` FOREIGN KEY (`member_id`) REFERENCES `athena`.`members` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
) COLLATE = 'utf8mb4_unicode_ci' ENGINE = InnoDB;